#ifndef __KINGPIN_STRUCT_H_
#define __KINGPIN_STRUCT_H_

#if !defined(__KINGPIN_KP_H_) && !defined(__KINGPIN_BACKEND)
#error "Do not include this file directly. Include types/kp.h instead."
#endif // __KINGPIN_KP_H_

#include <types/basic.h>

#ifdef __cplusplus
extern "C"
{
#endif // __cplusplus

    /// @brief A dependency structure for the Kingpin library
    /// @note This structure is used to provide the Kingpin library with
    /// functions it needs to perform critical operations, while still
    /// allowing the user to override them with their own functions and/or
    /// take advantage of performance optimizations provided elsewhere.
    /// @warning All functions marked as REQUIRED must be set, or the library
    /// will not be initialized. If the function is not required, it can be
    /// set to NULL.
    typedef struct _kp_dependency
    {
        /// @brief The function to use for memory allocation
        /// @param size The size of the memory to allocate
        /// @return A pointer to the allocated memory
        /// @warning This function is REQUIRED
        void *(*kp_malloc_fn)(kp_size size);

        /// @brief The function to use for memory reallocation
        /// @param ptr The pointer to the memory to reallocate
        /// @param size The new size of the memory
        /// @return A pointer to the reallocated memory
        /// @warning This function is OPTIONAL
        void *(*kp_realloc_fn)(void *ptr, kp_size size);

        /// @brief The function to use for memory deallocation
        /// @param ptr The pointer to the memory to deallocate
        /// @warning This function is REQUIRED
        void (*kp_free_fn)(void *ptr);

        /// @brief The function to use for memory copying
        /// @param dest The destination memory
        /// @param src The source memory
        /// @param size The size of the memory to copy
        /// @return A pointer to the destination memory
        /// @warning This function is OPTIONAL
        void *(*kp_memcpy_fn)(void *dest, const void *src, kp_size size);

        /// @brief The function to use for memory setting
        /// @param dest The destination memory
        /// @param value The value to set the memory to
        /// @param size The size of the memory to set
        /// @return A pointer to the destination memory
        /// @warning This function is OPTIONAL
        void *(*kp_memset_fn)(void *dest, s32 value, kp_size size);

        /// @brief The function to use for memory comparison
        /// @param dest The destination memory
        /// @param src The source memory
        /// @param size The size of the memory to compare
        /// @return A pointer to the destination memory
        /// @warning This function is OPTIONAL
        s32 (*kp_memcmp_fn)(const void *dest, const void *src, kp_size size);

        /// @brief The function to use for memory moving
        /// @param dest The destination memory
        /// @param src The source memory
        /// @param size The size of the memory to move
        /// @return A pointer to the destination memory
        /// @warning This function is OPTIONAL
        void *(*kp_memmove_fn)(void *dest, const void *src, kp_size size);

        /// @brief The function to use for getting entropy (cryptographically secure random data) for the internal RNG
        /// @param buffer The buffer to write the entropy to
        /// @param buffer_size The size of the buffer
        /// @return The number of bytes written to the buffer
        /// @warning This function is REQUIRED
        /// @note Not much entropy is needed, 32 bytes are required for every
        ///   16384 bytes generated by the internal RNG
        kp_size (*kp_get_entropy_fn)(u8 *buffer, kp_size buffer_size);
    } kp_dependency;

    typedef struct _kp_uninit
    {

    } kp_uninit;

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // __KINGPIN_STRUCT_H_